title: <p class="mfs-header-title">Welcome to Mindfire <span class="mfs-sub-title">Open Source</span></p>
description: Official GitHub Page for Mindfire Digital LLP.
             Explore our projects, contributions, and insights in technology, software development, and more. Join us in our journey to push the boundaries of innovation.
theme: jekyll-theme-cayman